version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sandy-leaveapproval-ACD"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ad3ixbr3ssv7"
s3_prefix = "sandy-leaveapproval-ACD"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
